import { Flight } from '@/types/flight'
import { Hotel } from '@/types/hotel'
import { Destination, Deal, Testimonial } from '@/types'
import { Booking } from '@/types/booking'

export const MOCK_FLIGHTS: Flight[] = [
  {
    id: 'fl-001',
    airline: 'Emirates',
    airlineCode: 'EK',
    flightNumber: 'EK 201',
    origin: 'JFK',
    originCity: 'New York',
    destination: 'DXB',
    destinationCity: 'Dubai',
    departureTime: '2024-06-15T22:00:00',
    arrivalTime: '2024-06-16T18:30:00',
    duration: '12h 30m',
    durationMinutes: 750,
    stops: 0,
    price: 890,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 12,
    aircraft: 'Boeing 777-300ER',
    baggage: { carry_on: '7 kg', checked: '30 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'USB Charging'],
    affiliateUrl: 'https://www.aviasales.com/search/JFKDXB20240615?marker=demo',
  },
  {
    id: 'fl-002',
    airline: 'Delta Airlines',
    airlineCode: 'DL',
    flightNumber: 'DL 400',
    origin: 'JFK',
    originCity: 'New York',
    destination: 'LHR',
    destinationCity: 'London',
    departureTime: '2024-06-15T19:00:00',
    arrivalTime: '2024-06-16T07:00:00',
    duration: '7h 00m',
    durationMinutes: 420,
    stops: 0,
    price: 650,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 8,
    aircraft: 'Airbus A330-300',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals'],
    affiliateUrl: 'https://www.aviasales.com/search/JFKLHR20240615?marker=demo',
  },
  {
    id: 'fl-003',
    airline: 'United Airlines',
    airlineCode: 'UA',
    flightNumber: 'UA 857',
    origin: 'LAX',
    originCity: 'Los Angeles',
    destination: 'NRT',
    destinationCity: 'Tokyo',
    departureTime: '2024-06-15T11:00:00',
    arrivalTime: '2024-06-16T15:30:00',
    duration: '11h 30m',
    durationMinutes: 690,
    stops: 0,
    price: 1150,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 5,
    aircraft: 'Boeing 787-9',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'USB Charging'],
    affiliateUrl: 'https://www.aviasales.com/search/LAXNRT20240615?marker=demo',
  },
  {
    id: 'fl-004',
    airline: 'British Airways',
    airlineCode: 'BA',
    flightNumber: 'BA 178',
    origin: 'LHR',
    originCity: 'London',
    destination: 'JFK',
    destinationCity: 'New York',
    departureTime: '2024-06-15T10:30:00',
    arrivalTime: '2024-06-15T13:30:00',
    duration: '8h 00m',
    durationMinutes: 480,
    stops: 0,
    price: 720,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 20,
    aircraft: 'Boeing 777-200',
    baggage: { carry_on: '12 kg', checked: '23 kg' },
    amenities: ['Entertainment', 'Meals', 'WiFi'],
    affiliateUrl: 'https://www.aviasales.com/search/LHRJFK20240615?marker=demo',
  },
  {
    id: 'fl-005',
    airline: 'Lufthansa',
    airlineCode: 'LH',
    flightNumber: 'LH 441',
    origin: 'FRA',
    originCity: 'Frankfurt',
    destination: 'JFK',
    destinationCity: 'New York',
    departureTime: '2024-06-15T12:00:00',
    arrivalTime: '2024-06-15T15:00:00',
    duration: '9h 00m',
    durationMinutes: 540,
    stops: 0,
    price: 680,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 15,
    aircraft: 'Airbus A340-600',
    baggage: { carry_on: '8 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals'],
    affiliateUrl: 'https://www.aviasales.com/search/FRAJFK20240615?marker=demo',
  },
  {
    id: 'fl-006',
    airline: 'Singapore Airlines',
    airlineCode: 'SQ',
    flightNumber: 'SQ 322',
    origin: 'SIN',
    originCity: 'Singapore',
    destination: 'LHR',
    destinationCity: 'London',
    departureTime: '2024-06-15T23:45:00',
    arrivalTime: '2024-06-16T06:30:00',
    duration: '13h 45m',
    durationMinutes: 825,
    stops: 0,
    price: 1280,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 7,
    aircraft: 'Airbus A350-900',
    baggage: { carry_on: '7 kg', checked: '30 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'USB Charging', 'Bar'],
    affiliateUrl: 'https://www.aviasales.com/search/SINLHR20240615?marker=demo',
  },
  {
    id: 'fl-007',
    airline: 'Air France',
    airlineCode: 'AF',
    flightNumber: 'AF 065',
    origin: 'CDG',
    originCity: 'Paris',
    destination: 'LAX',
    destinationCity: 'Los Angeles',
    departureTime: '2024-06-15T14:00:00',
    arrivalTime: '2024-06-15T17:00:00',
    duration: '11h 00m',
    durationMinutes: 660,
    stops: 0,
    price: 780,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 18,
    aircraft: 'Boeing 787-9',
    baggage: { carry_on: '12 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'Wine Service'],
    affiliateUrl: 'https://www.aviasales.com/search/CDGLAX20240615?marker=demo',
  },
  {
    id: 'fl-008',
    airline: 'Qatar Airways',
    airlineCode: 'QR',
    flightNumber: 'QR 704',
    origin: 'DOH',
    originCity: 'Doha',
    destination: 'SYD',
    destinationCity: 'Sydney',
    departureTime: '2024-06-15T02:00:00',
    arrivalTime: '2024-06-16T06:00:00',
    duration: '14h 00m',
    durationMinutes: 840,
    stops: 0,
    price: 1450,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 10,
    aircraft: 'Airbus A380',
    baggage: { carry_on: '7 kg', checked: '30 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'USB Charging', 'Bar'],
    affiliateUrl: 'https://www.aviasales.com/search/DOHSYD20240615?marker=demo',
  },
  {
    id: 'fl-009',
    airline: 'American Airlines',
    airlineCode: 'AA',
    flightNumber: 'AA 100',
    origin: 'JFK',
    originCity: 'New York',
    destination: 'LAX',
    destinationCity: 'Los Angeles',
    departureTime: '2024-06-15T07:00:00',
    arrivalTime: '2024-06-15T10:30:00',
    duration: '5h 30m',
    durationMinutes: 330,
    stops: 0,
    price: 280,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 25,
    aircraft: 'Boeing 737-800',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Snacks'],
    affiliateUrl: 'https://www.aviasales.com/search/JFKLAX20240615?marker=demo',
  },
  {
    id: 'fl-010',
    airline: 'Emirates',
    airlineCode: 'EK',
    flightNumber: 'EK 500',
    origin: 'DXB',
    originCity: 'Dubai',
    destination: 'BKK',
    destinationCity: 'Bangkok',
    departureTime: '2024-06-15T08:30:00',
    arrivalTime: '2024-06-15T15:30:00',
    duration: '6h 00m',
    durationMinutes: 360,
    stops: 0,
    price: 420,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 30,
    aircraft: 'Airbus A380',
    baggage: { carry_on: '7 kg', checked: '30 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'Bar'],
    affiliateUrl: 'https://www.aviasales.com/search/DXBBKK20240615?marker=demo',
  },
  {
    id: 'fl-011',
    airline: 'KLM',
    airlineCode: 'KL',
    flightNumber: 'KL 643',
    origin: 'AMS',
    originCity: 'Amsterdam',
    destination: 'JFK',
    destinationCity: 'New York',
    departureTime: '2024-06-15T09:00:00',
    arrivalTime: '2024-06-15T12:00:00',
    duration: '8h 00m',
    durationMinutes: 480,
    stops: 0,
    price: 710,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 14,
    aircraft: 'Boeing 787-9',
    baggage: { carry_on: '12 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals'],
    affiliateUrl: 'https://www.aviasales.com/search/AMSJFK20240615?marker=demo',
  },
  {
    id: 'fl-012',
    airline: 'Turkish Airlines',
    airlineCode: 'TK',
    flightNumber: 'TK 001',
    origin: 'IST',
    originCity: 'Istanbul',
    destination: 'LAX',
    destinationCity: 'Los Angeles',
    departureTime: '2024-06-15T01:00:00',
    arrivalTime: '2024-06-15T22:00:00',
    duration: '14h 00m',
    durationMinutes: 840,
    stops: 1,
    stopCities: ['London'],
    price: 890,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 22,
    aircraft: 'Boeing 777-300ER',
    baggage: { carry_on: '8 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals'],
    affiliateUrl: 'https://www.aviasales.com/search/ISTLAX20240615?marker=demo',
  },
  {
    id: 'fl-013',
    airline: 'Cathay Pacific',
    airlineCode: 'CX',
    flightNumber: 'CX 834',
    origin: 'HKG',
    originCity: 'Hong Kong',
    destination: 'LHR',
    destinationCity: 'London',
    departureTime: '2024-06-15T23:30:00',
    arrivalTime: '2024-06-16T05:30:00',
    duration: '12h 00m',
    durationMinutes: 720,
    stops: 0,
    price: 1100,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 9,
    aircraft: 'Airbus A350-900',
    baggage: { carry_on: '7 kg', checked: '30 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'USB Charging'],
    affiliateUrl: 'https://www.aviasales.com/search/HKGLHR20240615?marker=demo',
  },
  {
    id: 'fl-014',
    airline: 'Southwest Airlines',
    airlineCode: 'WN',
    flightNumber: 'WN 2500',
    origin: 'ORD',
    originCity: 'Chicago',
    destination: 'MIA',
    destinationCity: 'Miami',
    departureTime: '2024-06-15T06:00:00',
    arrivalTime: '2024-06-15T11:30:00',
    duration: '3h 30m',
    durationMinutes: 210,
    stops: 0,
    price: 180,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 40,
    aircraft: 'Boeing 737 MAX',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Snacks'],
    affiliateUrl: 'https://www.aviasales.com/search/ORDMIA20240615?marker=demo',
  },
  {
    id: 'fl-015',
    airline: 'Etihad Airways',
    airlineCode: 'EY',
    flightNumber: 'EY 103',
    origin: 'AUH',
    originCity: 'Abu Dhabi',
    destination: 'LHR',
    destinationCity: 'London',
    departureTime: '2024-06-15T09:00:00',
    arrivalTime: '2024-06-15T13:30:00',
    duration: '7h 30m',
    durationMinutes: 450,
    stops: 0,
    price: 820,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 16,
    aircraft: 'Airbus A380',
    baggage: { carry_on: '7 kg', checked: '30 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'Bar'],
    affiliateUrl: 'https://www.aviasales.com/search/AUHLHR20240615?marker=demo',
  },
  {
    id: 'fl-016',
    airline: 'Air Canada',
    airlineCode: 'AC',
    flightNumber: 'AC 855',
    origin: 'YYZ',
    originCity: 'Toronto',
    destination: 'LHR',
    destinationCity: 'London',
    departureTime: '2024-06-15T21:00:00',
    arrivalTime: '2024-06-16T09:30:00',
    duration: '7h 30m',
    durationMinutes: 450,
    stops: 0,
    price: 580,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 19,
    aircraft: 'Boeing 787-8',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals'],
    affiliateUrl: 'https://www.aviasales.com/search/YYZLHR20240615?marker=demo',
  },
  {
    id: 'fl-017',
    airline: 'Qantas',
    airlineCode: 'QF',
    flightNumber: 'QF 002',
    origin: 'SYD',
    originCity: 'Sydney',
    destination: 'LHR',
    destinationCity: 'London',
    departureTime: '2024-06-15T16:00:00',
    arrivalTime: '2024-06-16T05:00:00',
    duration: '24h 00m',
    durationMinutes: 1440,
    stops: 1,
    stopCities: ['Dubai'],
    price: 1680,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 11,
    aircraft: 'Airbus A380',
    baggage: { carry_on: '7 kg', checked: '30 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'USB Charging'],
    affiliateUrl: 'https://www.aviasales.com/search/SYDLHR20240615?marker=demo',
  },
  {
    id: 'fl-018',
    airline: 'Iberia',
    airlineCode: 'IB',
    flightNumber: 'IB 6251',
    origin: 'MAD',
    originCity: 'Madrid',
    destination: 'JFK',
    destinationCity: 'New York',
    departureTime: '2024-06-15T11:00:00',
    arrivalTime: '2024-06-15T14:00:00',
    duration: '9h 00m',
    durationMinutes: 540,
    stops: 0,
    price: 660,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 23,
    aircraft: 'Airbus A330-200',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals'],
    affiliateUrl: 'https://www.aviasales.com/search/MADJFK20240615?marker=demo',
  },
  {
    id: 'fl-019',
    airline: 'Delta Airlines',
    airlineCode: 'DL',
    flightNumber: 'DL 207',
    origin: 'LAX',
    originCity: 'Los Angeles',
    destination: 'CDG',
    destinationCity: 'Paris',
    departureTime: '2024-06-15T17:30:00',
    arrivalTime: '2024-06-16T14:00:00',
    duration: '10h 30m',
    durationMinutes: 630,
    stops: 0,
    price: 820,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 17,
    aircraft: 'Airbus A350-900',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals'],
    affiliateUrl: 'https://www.aviasales.com/search/LAXCDG20240615?marker=demo',
  },
  {
    id: 'fl-020',
    airline: 'Korean Air',
    airlineCode: 'KE',
    flightNumber: 'KE 081',
    origin: 'ICN',
    originCity: 'Seoul',
    destination: 'JFK',
    destinationCity: 'New York',
    departureTime: '2024-06-15T13:00:00',
    arrivalTime: '2024-06-15T17:00:00',
    duration: '14h 00m',
    durationMinutes: 840,
    stops: 0,
    price: 1050,
    currency: 'USD',
    cabinClass: 'economy',
    seatsAvailable: 6,
    aircraft: 'Boeing 787-9',
    baggage: { carry_on: '10 kg', checked: '23 kg' },
    amenities: ['WiFi', 'Entertainment', 'Meals', 'USB Charging'],
    affiliateUrl: 'https://www.aviasales.com/search/ICNJFK20240615?marker=demo',
  },
]

export const MOCK_HOTELS: Hotel[] = [
  {
    id: 'ht-001',
    name: 'The Ritz-Carlton New York',
    description:
      'Situated in the heart of Manhattan, The Ritz-Carlton offers unparalleled luxury with breathtaking views of Central Park. Experience world-class dining, spa services, and impeccable attention to detail.',
    location: 'Midtown Manhattan, New York',
    city: 'New York',
    country: 'United States',
    address: '50 Central Park South, New York, NY 10019',
    stars: 5,
    rating: 4.8,
    reviewCount: 2847,
    pricePerNight: 450,
    currency: 'USD',
    amenities: ['WiFi', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Concierge', 'Room Service'],
    images: ['gradient-blue-purple', 'gradient-indigo'],
    roomTypes: [
      { id: 'r1', name: 'Deluxe Room', description: 'Elegant room with city views', price: 450, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Minibar', 'Safe'] },
      { id: 'r2', name: 'Central Park Suite', description: 'Spacious suite with park views', price: 850, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Minibar', 'Bathtub', 'Safe'] },
    ],
    coordinates: { lat: 40.7651, lng: -73.9766 },
    affiliateUrl: 'https://www.booking.com/hotel/us/ritz-carlton-new-york.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available for $45 per person',
      pets: 'Pets allowed (fees apply)',
    },
  },
  {
    id: 'ht-002',
    name: 'Burj Al Arab Jumeirah',
    description:
      'The world\'s most iconic hotel, standing on its own island and offering the ultimate in Arabian luxury. Experience butler service, underwater dining, and extraordinary suites.',
    location: 'Jumeirah Beach, Dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    address: 'Jumeirah Beach Road, Dubai, UAE',
    stars: 5,
    rating: 4.9,
    reviewCount: 1543,
    pricePerNight: 1800,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Private Beach', 'Butler Service'],
    images: ['gradient-gold-orange', 'gradient-warm'],
    roomTypes: [
      { id: 'r1', name: 'Deluxe Suite', description: 'Two-floor suite with sea views', price: 1800, capacity: 2, bedType: 'King', amenities: ['Butler', 'WiFi', 'Jacuzzi'] },
      { id: 'r2', name: 'Panoramic Suite', description: 'Top floor suite with 360° views', price: 3200, capacity: 4, bedType: 'King', amenities: ['Butler', 'WiFi', 'Private Terrace'] },
    ],
    coordinates: { lat: 25.1412, lng: 55.1853 },
    affiliateUrl: 'https://www.booking.com/hotel/ae/burj-al-arab.html?aid=demo',
    checkIn: '14:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 7 days before check-in',
      breakfast: 'Breakfast included in all rates',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-003',
    name: 'The Savoy London',
    description:
      'London\'s most celebrated hotel, where tradition meets modernity. Located on the Strand with stunning views of the Thames, offering world-famous afternoon tea and the iconic American Bar.',
    location: 'The Strand, London',
    city: 'London',
    country: 'United Kingdom',
    address: 'Strand, London WC2R 0EU, UK',
    stars: 5,
    rating: 4.7,
    reviewCount: 3215,
    pricePerNight: 580,
    currency: 'USD',
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Spa', 'Gym', 'Concierge', 'Pool'],
    images: ['gradient-emerald-teal', 'gradient-green'],
    roomTypes: [
      { id: 'r1', name: 'Superior Room', description: 'Classic London room', price: 580, capacity: 2, bedType: 'Queen', amenities: ['WiFi', 'Safe'] },
      { id: 'r2', name: 'River View Suite', description: 'Suite with Thames views', price: 1200, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Safe', 'Lounge'] },
    ],
    coordinates: { lat: 51.5110, lng: -0.1207 },
    affiliateUrl: 'https://www.booking.com/hotel/gb/the-savoy.html?aid=demo',
    checkIn: '15:00',
    checkOut: '11:00',
    policies: {
      cancellation: 'Free cancellation up to 3 days before check-in',
      breakfast: 'Continental breakfast available for £35',
      pets: 'Dogs welcome (fees apply)',
    },
  },
  {
    id: 'ht-004',
    name: 'Four Seasons George V Paris',
    description:
      'An iconic Parisian palace hotel steps from the Champs-Élysées. Marvel at the exquisite floral arrangements, Michelin-starred dining, and breathtaking views of the Eiffel Tower.',
    location: '8th Arrondissement, Paris',
    city: 'Paris',
    country: 'France',
    address: '31 Avenue George V, 75008 Paris, France',
    stars: 5,
    rating: 4.9,
    reviewCount: 2103,
    pricePerNight: 920,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Concierge', 'Room Service'],
    images: ['gradient-rose-pink', 'gradient-red'],
    roomTypes: [
      { id: 'r1', name: 'Superior Room', description: 'Elegant Parisian room', price: 920, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Minibar'] },
      { id: 'r2', name: 'Eiffel Suite', description: 'Suite with Eiffel Tower views', price: 2100, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Terrace', 'Butler'] },
    ],
    coordinates: { lat: 48.8668, lng: 2.3006 },
    affiliateUrl: 'https://www.booking.com/hotel/fr/four-seasons-george-v-paris.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 5 days before check-in',
      breakfast: 'Breakfast included for stays 3+ nights',
      pets: 'Pets allowed',
    },
  },
  {
    id: 'ht-005',
    name: 'Marina Bay Sands Singapore',
    description:
      'Singapore\'s most iconic hotel featuring the world-famous infinity pool on the 57th floor, three restaurant towers, and panoramic city views. A true architectural marvel.',
    location: 'Marina Bay, Singapore',
    city: 'Singapore',
    country: 'Singapore',
    address: '10 Bayfront Avenue, Singapore 018956',
    stars: 5,
    rating: 4.6,
    reviewCount: 8932,
    pricePerNight: 380,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Casino', 'Shopping Mall'],
    images: ['gradient-cyan-blue', 'gradient-ocean'],
    roomTypes: [
      { id: 'r1', name: 'Deluxe Room', description: 'City view room', price: 380, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Safe'] },
      { id: 'r2', name: 'Premier Suite', description: 'Suite with infinity pool access', price: 780, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Lounge Access'] },
    ],
    coordinates: { lat: 1.2834, lng: 103.8607 },
    affiliateUrl: 'https://www.booking.com/hotel/sg/marina-bay-sands.html?aid=demo',
    checkIn: '15:00',
    checkOut: '11:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from S$45',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-006',
    name: 'Park Hyatt Tokyo',
    description:
      'Set within the sleek Shinjuku Park Tower, this refined hotel offers spectacular views of Mount Fuji and the Tokyo skyline. Famous for inspiring Lost in Translation.',
    location: 'Shinjuku, Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    address: '3-7-1-2 Nishi-Shinjuku, Shinjuku, Tokyo 163-1055',
    stars: 5,
    rating: 4.8,
    reviewCount: 1876,
    pricePerNight: 490,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Concierge'],
    images: ['gradient-purple-indigo', 'gradient-violet'],
    roomTypes: [
      { id: 'r1', name: 'Park Deluxe Room', description: 'Elegant room with city views', price: 490, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Minibar'] },
      { id: 'r2', name: 'Park Suite', description: 'Spacious suite with Mt Fuji views', price: 950, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Dining Area'] },
    ],
    coordinates: { lat: 35.6897, lng: 139.6919 },
    affiliateUrl: 'https://www.booking.com/hotel/jp/park-hyatt-tokyo.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from ¥4500',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-007',
    name: 'W Barcelona',
    description:
      'An architectural masterpiece shaped like a sail, jutting into the Mediterranean Sea. W Barcelona blends cutting-edge design with the vibrant energy of Barcelona\'s beach culture.',
    location: 'Barceloneta Beach, Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    address: 'Plaça de la Rosa dels Vents 1, 08039 Barcelona, Spain',
    stars: 5,
    rating: 4.5,
    reviewCount: 4321,
    pricePerNight: 320,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Private Beach'],
    images: ['gradient-orange-red', 'gradient-sunset'],
    roomTypes: [
      { id: 'r1', name: 'Wonderful Room', description: 'City or sea view room', price: 320, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Safe'] },
      { id: 'r2', name: 'Fabulous Suite', description: 'Suite with panoramic sea views', price: 680, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Terrace', 'Jacuzzi'] },
    ],
    coordinates: { lat: 41.3766, lng: 2.1907 },
    affiliateUrl: 'https://www.booking.com/hotel/es/w-barcelona.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from €35',
      pets: 'Pets allowed',
    },
  },
  {
    id: 'ht-008',
    name: 'Aman Tokyo',
    description:
      'Occupying the top six floors of the Otemachi Tower, Aman Tokyo blends traditional Japanese aesthetics with contemporary design. An urban sanctuary with extraordinary city views.',
    location: 'Otemachi, Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    address: 'The Otemachi Tower, 1-5-6 Otemachi, Chiyoda, Tokyo',
    stars: 5,
    rating: 4.9,
    reviewCount: 987,
    pricePerNight: 780,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Concierge', 'Butler Service'],
    images: ['gradient-slate-gray', 'gradient-neutral'],
    roomTypes: [
      { id: 'r1', name: 'Aman Suite', description: 'Serene suite with city panorama', price: 780, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Ofuro Bath'] },
    ],
    coordinates: { lat: 35.6865, lng: 139.7635 },
    affiliateUrl: 'https://www.booking.com/hotel/jp/aman-tokyo.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 7 days before check-in',
      breakfast: 'Breakfast included in all rates',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-009',
    name: 'Atlantis The Palm Dubai',
    description:
      'The iconic palm-shaped resort that redefined luxury hospitality. Atlantis offers an unmatched water park, underwater suites, and world-class dining in the heart of Dubai.',
    location: 'Palm Jumeirah, Dubai',
    city: 'Dubai',
    country: 'United Arab Emirates',
    address: 'Crescent Road, Palm Jumeirah, Dubai, UAE',
    stars: 5,
    rating: 4.4,
    reviewCount: 12543,
    pricePerNight: 280,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Water Park', 'Private Beach', 'Aquarium'],
    images: ['gradient-aqua-teal', 'gradient-sea'],
    roomTypes: [
      { id: 'r1', name: 'Reef Club Room', description: 'Room with aquarium views', price: 280, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Safe'] },
      { id: 'r2', name: 'Underwater Suite', description: 'Suite surrounded by marine life', price: 2500, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Aquarium View'] },
    ],
    coordinates: { lat: 25.1304, lng: 55.1173 },
    affiliateUrl: 'https://www.booking.com/hotel/ae/atlantis-the-palm.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from AED 180',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-010',
    name: 'The Peninsula New York',
    description:
      'A storied landmark of New York luxury, The Peninsula occupies a prime position on Fifth Avenue. Experience refined elegance, stunning rooftop views, and impeccable service.',
    location: 'Fifth Avenue, New York',
    city: 'New York',
    country: 'United States',
    address: '700 Fifth Avenue, New York, NY 10019',
    stars: 5,
    rating: 4.7,
    reviewCount: 1654,
    pricePerNight: 495,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Concierge', 'Helicopter Transfers'],
    images: ['gradient-amber-gold', 'gradient-yellow'],
    roomTypes: [
      { id: 'r1', name: 'Superior Room', description: 'Classic New York elegance', price: 495, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Minibar'] },
    ],
    coordinates: { lat: 40.7617, lng: -73.9759 },
    affiliateUrl: 'https://www.booking.com/hotel/us/the-peninsula-new-york.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from $55',
      pets: 'Pets allowed',
    },
  },
  {
    id: 'ht-011',
    name: 'Raffles Hotel Singapore',
    description:
      'The legendary grande dame of Singapore hospitality, where history and luxury intertwine. Home of the original Singapore Sling, this colonial landmark is a national monument.',
    location: 'City Hall, Singapore',
    city: 'Singapore',
    country: 'Singapore',
    address: '1 Beach Road, Singapore 189673',
    stars: 5,
    rating: 4.8,
    reviewCount: 3421,
    pricePerNight: 620,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Concierge', 'Butler Service'],
    images: ['gradient-cream-white', 'gradient-light'],
    roomTypes: [
      { id: 'r1', name: 'Palm Court Suite', description: 'Classic colonial suite', price: 620, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Living Room'] },
    ],
    coordinates: { lat: 1.2942, lng: 103.8520 },
    affiliateUrl: 'https://www.booking.com/hotel/sg/raffles.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 72 hours before check-in',
      breakfast: 'Breakfast included in all suites',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-012',
    name: 'Hotel Danieli Venice',
    description:
      'Set in a Gothic palazzo on the Grand Canal, Hotel Danieli is one of the most romantic hotels in the world. Experience Venice\'s timeless beauty from this legendary property.',
    location: 'San Marco, Venice',
    city: 'Venice',
    country: 'Italy',
    address: 'Riva degli Schiavoni, 4196, 30122 Venice VE, Italy',
    stars: 5,
    rating: 4.6,
    reviewCount: 2876,
    pricePerNight: 680,
    currency: 'USD',
    amenities: ['WiFi', 'Restaurant', 'Bar', 'Spa', 'Concierge', 'Boat Transfers'],
    images: ['gradient-warm-gold', 'gradient-terracotta'],
    roomTypes: [
      { id: 'r1', name: 'Classic Room', description: 'Venetian Gothic elegance', price: 680, capacity: 2, bedType: 'Queen', amenities: ['WiFi', 'Safe'] },
      { id: 'r2', name: 'Lagoon View Suite', description: 'Suite with Grand Canal views', price: 1450, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Terrace'] },
    ],
    coordinates: { lat: 45.4336, lng: 12.3409 },
    affiliateUrl: 'https://www.booking.com/hotel/it/danieli-venice.html?aid=demo',
    checkIn: '14:00',
    checkOut: '11:00',
    policies: {
      cancellation: 'Free cancellation up to 5 days before check-in',
      breakfast: 'Breakfast available from €45',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-013',
    name: 'Amangiri Utah',
    description:
      'A canyon sanctuary nestled among the ancient formations of the American Southwest. Amangiri offers a transformative desert experience unlike anything else in the world.',
    location: 'Canyon Point, Utah',
    city: 'Canyon Point',
    country: 'United States',
    address: '1 Kayenta Rd, Canyon Point, UT 84741',
    stars: 5,
    rating: 4.9,
    reviewCount: 654,
    pricePerNight: 1600,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Helicopter Tours', 'Guided Hikes'],
    images: ['gradient-desert-sand', 'gradient-earth'],
    roomTypes: [
      { id: 'r1', name: 'Suite', description: 'Desert oasis suite', price: 1600, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Plunge Pool'] },
    ],
    coordinates: { lat: 37.0042, lng: -111.6672 },
    affiliateUrl: 'https://www.booking.com/hotel/us/amangiri.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 30 days before check-in',
      breakfast: 'Breakfast included in all rates',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-014',
    name: 'The Oberoi Udaivilas',
    description:
      'Set on the banks of Lake Pichola, this stunning palatial resort embodies the grandeur of Rajasthan. Hand-painted frescoes, private pools, and views of the City Palace await.',
    location: 'Lake Pichola, Udaipur',
    city: 'Udaipur',
    country: 'India',
    address: 'Haridasji Ki Magri, Udaipur, Rajasthan 313001, India',
    stars: 5,
    rating: 4.9,
    reviewCount: 1234,
    pricePerNight: 480,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Boat Trips', 'Butler Service'],
    images: ['gradient-marigold', 'gradient-saffron'],
    roomTypes: [
      { id: 'r1', name: 'Premier Lake View Room', description: 'Room with lake views', price: 480, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler'] },
      { id: 'r2', name: 'Kohinoor Suite', description: 'Suite with private pool', price: 1200, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Private Pool'] },
    ],
    coordinates: { lat: 24.5762, lng: 73.6811 },
    affiliateUrl: 'https://www.booking.com/hotel/in/oberoi-udaivilas-udaipur.html?aid=demo',
    checkIn: '14:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 5 days before check-in',
      breakfast: 'Breakfast included in all rates',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-015',
    name: 'Six Senses Zil Pasyon',
    description:
      'A private island retreat on Félicité Island in the Seychelles. Six Senses Zil Pasyon is a sanctuary of barefoot luxury with pristine beaches and extraordinary marine life.',
    location: 'Félicité Island, Seychelles',
    city: 'Félicité',
    country: 'Seychelles',
    address: 'Félicité Island, Seychelles',
    stars: 5,
    rating: 4.9,
    reviewCount: 432,
    pricePerNight: 2200,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Private Beach', 'Diving Center', 'Yoga'],
    images: ['gradient-turquoise-sea', 'gradient-tropical'],
    roomTypes: [
      { id: 'r1', name: 'Hilltop Ocean View Villa', description: 'Villa with ocean panorama', price: 2200, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Private Pool', 'Butler'] },
    ],
    coordinates: { lat: -4.3242, lng: 55.8631 },
    affiliateUrl: 'https://www.booking.com/hotel/sc/six-senses-zil-pasyon.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 30 days before check-in',
      breakfast: 'All meals included in rates',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-016',
    name: 'Hotel Arts Barcelona',
    description:
      'A contemporary landmark on the Barcelona waterfront. Hotel Arts towers above the Mediterranean offering world-class art collections, superb dining, and a beautiful beach club.',
    location: 'Olympic Village, Barcelona',
    city: 'Barcelona',
    country: 'Spain',
    address: 'Carrer de la Marina, 19-21, 08005 Barcelona, Spain',
    stars: 5,
    rating: 4.6,
    reviewCount: 5678,
    pricePerNight: 290,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Private Beach', 'Tennis'],
    images: ['gradient-mediterranean', 'gradient-azure'],
    roomTypes: [
      { id: 'r1', name: 'Sea View Room', description: 'Bright room with sea views', price: 290, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Minibar'] },
    ],
    coordinates: { lat: 41.3843, lng: 2.1958 },
    affiliateUrl: 'https://www.booking.com/hotel/es/arts-barcelona.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from €38',
      pets: 'Pets allowed',
    },
  },
  {
    id: 'ht-017',
    name: 'Mandarin Oriental Bangkok',
    description:
      'One of the world\'s great hotels, the Mandarin Oriental Bangkok has welcomed luminaries for over 140 years. Its riverside setting, legendary service, and elegant rooms are unmatched.',
    location: 'Riverside, Bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    address: '48 Oriental Avenue, Bang Rak, Bangkok 10500, Thailand',
    stars: 5,
    rating: 4.8,
    reviewCount: 4321,
    pricePerNight: 220,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'River Views', 'Cooking School'],
    images: ['gradient-golden-thai', 'gradient-amber'],
    roomTypes: [
      { id: 'r1', name: 'Superior Room', description: 'River wing room with garden views', price: 220, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Safe'] },
      { id: 'r2', name: 'Suite Authors Wing', description: 'Historic suite named after famous guests', price: 580, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Lounge'] },
    ],
    coordinates: { lat: 13.7268, lng: 100.5132 },
    affiliateUrl: 'https://www.booking.com/hotel/th/mandarin-oriental-bangkok.html?aid=demo',
    checkIn: '14:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from THB 850',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-018',
    name: 'Belmond Hotel Cipriani Venice',
    description:
      'A serene oasis on Giudecca Island with breathtaking views across to St Mark\'s and the Doge\'s Palace. Accessible only by private launch, this is Venice\'s most coveted address.',
    location: 'Giudecca Island, Venice',
    city: 'Venice',
    country: 'Italy',
    address: 'Giudecca 10, 30133 Venice, Italy',
    stars: 5,
    rating: 4.8,
    reviewCount: 1876,
    pricePerNight: 960,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Private Launch', 'Tennis'],
    images: ['gradient-venetian-blue', 'gradient-lagoon'],
    roomTypes: [
      { id: 'r1', name: 'Classic Room', description: 'Elegant room with garden views', price: 960, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Safe'] },
    ],
    coordinates: { lat: 45.4288, lng: 12.3299 },
    affiliateUrl: 'https://www.booking.com/hotel/it/cipriani-venice.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 7 days before check-in',
      breakfast: 'Breakfast included in all rates',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-019',
    name: 'Banyan Tree Samui',
    description:
      'Perched on the hillside of Ko Samui with panoramic Gulf of Thailand views, Banyan Tree offers the finest all-pool villas in Thailand with an award-winning spa.',
    location: 'Chaweng Noi, Ko Samui',
    city: 'Ko Samui',
    country: 'Thailand',
    address: '99/9 Moo 4, Ban Taling Ngam, Ko Samui, Surat Thani 84140',
    stars: 5,
    rating: 4.7,
    reviewCount: 2345,
    pricePerNight: 350,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Private Pool Villas', 'Cooking Classes'],
    images: ['gradient-tropical-green', 'gradient-jungle'],
    roomTypes: [
      { id: 'r1', name: 'Seaview Pool Villa', description: 'Villa with private pool and sea views', price: 350, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Private Pool', 'Butler'] },
    ],
    coordinates: { lat: 9.4882, lng: 100.0617 },
    affiliateUrl: 'https://www.booking.com/hotel/th/banyan-tree-samui.html?aid=demo',
    checkIn: '15:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast included in villa rates',
      pets: 'Pets not allowed',
    },
  },
  {
    id: 'ht-020',
    name: 'Waldorf Astoria Beverly Hills',
    description:
      'A sleek, contemporary tower in the heart of Beverly Hills offering impeccable California luxury. With rooftop pool, celebrity-frequented spa, and Michelin-starred dining.',
    location: 'Beverly Hills, Los Angeles',
    city: 'Los Angeles',
    country: 'United States',
    address: '9850 Wilshire Blvd, Beverly Hills, CA 90210',
    stars: 5,
    rating: 4.7,
    reviewCount: 2109,
    pricePerNight: 520,
    currency: 'USD',
    amenities: ['WiFi', 'Pool', 'Spa', 'Restaurant', 'Gym', 'Bar', 'Valet Parking', 'Concierge'],
    images: ['gradient-california-gold', 'gradient-sunshine'],
    roomTypes: [
      { id: 'r1', name: 'Deluxe Room', description: 'Contemporary LA elegance', price: 520, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Minibar', 'Safe'] },
      { id: 'r2', name: 'Beverly Hills Suite', description: 'Iconic suite with skyline views', price: 1100, capacity: 2, bedType: 'King', amenities: ['WiFi', 'Butler', 'Private Terrace'] },
    ],
    coordinates: { lat: 34.0638, lng: -118.4010 },
    affiliateUrl: 'https://www.booking.com/hotel/us/waldorf-astoria-beverly-hills.html?aid=demo',
    checkIn: '16:00',
    checkOut: '12:00',
    policies: {
      cancellation: 'Free cancellation up to 48 hours before check-in',
      breakfast: 'Breakfast available from $45',
      pets: 'Pets allowed (fee applies)',
    },
  },
]

export const POPULAR_DESTINATIONS: Destination[] = [
  {
    id: 'dest-001',
    name: 'Dubai',
    country: 'UAE',
    code: 'DXB',
    description: 'A city of superlatives with iconic skyscrapers and luxury shopping',
    startingPrice: 450,
    currency: 'USD',
    gradient: 'from-amber-400 to-orange-500',
  },
  {
    id: 'dest-002',
    name: 'Paris',
    country: 'France',
    code: 'CDG',
    description: 'The city of light, romance, and world-class culture',
    startingPrice: 380,
    currency: 'USD',
    gradient: 'from-pink-400 to-rose-500',
  },
  {
    id: 'dest-003',
    name: 'Tokyo',
    country: 'Japan',
    code: 'NRT',
    description: 'Where ancient traditions blend with futuristic technology',
    startingPrice: 620,
    currency: 'USD',
    gradient: 'from-indigo-400 to-purple-500',
  },
  {
    id: 'dest-004',
    name: 'New York',
    country: 'USA',
    code: 'JFK',
    description: 'The city that never sleeps, full of energy and opportunity',
    startingPrice: 280,
    currency: 'USD',
    gradient: 'from-blue-400 to-cyan-500',
  },
  {
    id: 'dest-005',
    name: 'Bali',
    country: 'Indonesia',
    code: 'DPS',
    description: 'Tropical paradise with stunning temples and pristine beaches',
    startingPrice: 390,
    currency: 'USD',
    gradient: 'from-green-400 to-emerald-500',
  },
  {
    id: 'dest-006',
    name: 'London',
    country: 'UK',
    code: 'LHR',
    description: 'Historic capital rich in culture, history, and diversity',
    startingPrice: 320,
    currency: 'USD',
    gradient: 'from-teal-400 to-cyan-500',
  },
  {
    id: 'dest-007',
    name: 'Santorini',
    country: 'Greece',
    code: 'JTR',
    description: 'Breathtaking volcanic island with iconic white architecture',
    startingPrice: 450,
    currency: 'USD',
    gradient: 'from-sky-400 to-blue-500',
  },
  {
    id: 'dest-008',
    name: 'Maldives',
    country: 'Maldives',
    code: 'MLE',
    description: 'Crystal clear waters and overwater bungalows in paradise',
    startingPrice: 890,
    currency: 'USD',
    gradient: 'from-cyan-400 to-teal-500',
  },
]

export const TRAVEL_DEALS: Deal[] = [
  {
    id: 'deal-001',
    title: 'Dubai Winter Escape',
    description: 'Fly to Dubai and stay at a 5-star resort with pool access',
    originalPrice: 1200,
    discountedPrice: 850,
    discount: 29,
    type: 'flight',
    destination: 'Dubai',
    validUntil: '2024-12-31',
    gradient: 'from-amber-400 to-orange-500',
  },
  {
    id: 'deal-002',
    title: 'Paris Romance Package',
    description: 'Round-trip flights + 3 nights boutique hotel near Eiffel Tower',
    originalPrice: 1800,
    discountedPrice: 1290,
    discount: 28,
    type: 'hotel',
    destination: 'Paris',
    validUntil: '2024-11-30',
    gradient: 'from-pink-400 to-rose-500',
  },
  {
    id: 'deal-003',
    title: 'Tokyo Cherry Blossom',
    description: 'Experience spring in Japan with flights from $620',
    originalPrice: 950,
    discountedPrice: 620,
    discount: 35,
    type: 'flight',
    destination: 'Tokyo',
    validUntil: '2024-04-15',
    gradient: 'from-indigo-400 to-purple-500',
  },
  {
    id: 'deal-004',
    title: 'Maldives Luxury Retreat',
    description: 'Overwater villa deal — save 30% on 7-night stays',
    originalPrice: 4200,
    discountedPrice: 2940,
    discount: 30,
    type: 'hotel',
    destination: 'Maldives',
    validUntil: '2024-10-31',
    gradient: 'from-cyan-400 to-teal-500',
  },
  {
    id: 'deal-005',
    title: 'New York City Break',
    description: 'Weekend getaway with flights and Times Square hotel',
    originalPrice: 680,
    discountedPrice: 480,
    discount: 29,
    type: 'hotel',
    destination: 'New York',
    validUntil: '2024-12-15',
    gradient: 'from-blue-400 to-cyan-500',
  },
  {
    id: 'deal-006',
    title: 'Bali Wellness Journey',
    description: 'Flights + 5 nights luxury villa with spa credit',
    originalPrice: 2100,
    discountedPrice: 1450,
    discount: 31,
    type: 'hotel',
    destination: 'Bali',
    validUntil: '2024-11-15',
    gradient: 'from-green-400 to-emerald-500',
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    name: 'Sarah Mitchell',
    initials: 'SM',
    location: 'Los Angeles, CA',
    rating: 5,
    review:
      "AlterTravel saved me over $400 on my Paris trip! The interface is incredibly intuitive and I found the perfect hotel within minutes. Will definitely use again for my next adventure.",
    tripType: 'Leisure - Paris',
    date: '2024-03-15',
  },
  {
    id: 'test-002',
    name: 'James Chen',
    initials: 'JC',
    location: 'San Francisco, CA',
    rating: 5,
    review:
      "Found an amazing deal on a business class flight to Tokyo. The filters made it easy to narrow down exactly what I was looking for. Customer support was also excellent.",
    tripType: 'Business - Tokyo',
    date: '2024-02-28',
  },
  {
    id: 'test-003',
    name: 'Emma Thompson',
    initials: 'ET',
    location: 'London, UK',
    rating: 4,
    review:
      "Booked our honeymoon to the Maldives through AlterTravel. The hotel selection was outstanding and the price was the best we found anywhere. Truly a dream experience!",
    tripType: 'Honeymoon - Maldives',
    date: '2024-01-20',
  },
  {
    id: 'test-004',
    name: 'Michael Rodriguez',
    initials: 'MR',
    location: 'Miami, FL',
    rating: 5,
    review:
      "I travel frequently for work and AlterTravel has become my go-to booking platform. The saved searches feature and quick rebooking saves me so much time each week.",
    tripType: 'Business Travel',
    date: '2024-03-01',
  },
]

export const MOCK_BOOKINGS: Booking[] = [
  {
    id: 'bk-001',
    userId: 'user-001',
    type: 'flight',
    status: 'confirmed',
    details: {
      flight: MOCK_FLIGHTS[0],
      passengers: [{ firstName: 'John', lastName: 'Doe', dateOfBirth: '1990-01-15', nationality: 'US', email: 'john@example.com', phone: '+1234567890' }],
      departureDate: '2024-06-15',
      cabinClass: 'economy',
    },
    totalPrice: 890,
    currency: 'USD',
    affiliateId: 'demo',
    commission: 26.7,
    createdAt: '2024-03-10T10:00:00Z',
    updatedAt: '2024-03-10T10:05:00Z',
  },
  {
    id: 'bk-002',
    userId: 'user-001',
    type: 'hotel',
    status: 'confirmed',
    details: {
      hotel: MOCK_HOTELS[0],
      roomType: 'Deluxe Room',
      checkIn: '2024-06-15',
      checkOut: '2024-06-20',
      guests: [{ firstName: 'John', lastName: 'Doe', email: 'john@example.com', phone: '+1234567890' }],
      rooms: 1,
    },
    totalPrice: 2250,
    currency: 'USD',
    affiliateId: 'demo',
    commission: 135,
    createdAt: '2024-03-11T14:00:00Z',
    updatedAt: '2024-03-11T14:05:00Z',
  },
]
